CREATE DATABASE biblioteca;
CREATE TABLE autores(id SERIAL, nombre VARCHAR(100) NOT NULL);
ALTER TABLE autores ADD PRIMARY KEY(id);
CREATE TABLE libros(codigo INT, nombre VARCHAR(100) NOT NULL, PRIMARY KEY(codigo));
CREATE TABLE lectores(id SERIAL, nombre VARCHAR(100) NOT NULL, PRIMARY KEY(id));
